### ISSUE TITLE
ESM issue with Next.js back in v.2.2.0

### ISSUE THREAD

**Issue by LJNGDAHL** [sanity-io/sanity-plugin-mux-input#310] opened 2023-08-17 11:56 UTC
This, or a similar issue, was fixed in `v.2.0.15` as mentioned [here](https://github.com/sanity-io/sanity-plugin-mux-input/issues/215#issuecomment-1447657668) but it seems to have re-appeared in `v.2.2.0`. For me, using `v.2.2.1` works, but after that I get ESM related errors and the app crashes.

I have tried adding `esmExternals: 'loose'` in the next.config.js but it does not solve the issue for me.

![Screenshot by Dropbox Capture](https://github.com/sanity-io/sanity-plugin-mux-input/assets/18701520/57e1b1b4-2467-4dd4-b165-76b9e97bc3dc)

### Versions
 
```
next: 13.4.12
sanity: 3.14.0
```

**Comment by modulareverything** [comment] 2023-11-09 08:20
This error goes away for me if I downgrade to `2.2.2`, but seems to appear if I use the `2.2.3` package.

**Comment by hdoro** [comment] 2024-05-03 11:37
Duplicate of #274

**Closed by hdoro** 2024-05-03 11:37 UTC
Labels: triaged
