### ISSUE TITLE
Can't remove items from media library

### ISSUE THREAD

**Issue by patrickdaley** [sanity-io/sanity-plugin-mux-input#11] opened 2020-02-21 23:38 UTC
It looks like the draft that contains the interface for removing items blocks the removal action:

"The mutation(s) failed: Document "b430b968-9037-44ab-9878-28376fb86d08" cannot be deleted as there are references to it from "drafts.b32572a0-8c4f-43f5-acc1-edf0f6ac9b64""

**Comment by kmelve** [comment] 2020-02-24 08:44
Thanks for reporting @patrickdaley! This is probably a “not a bug, but a feature”. The backend doesn't let you remove documents with incoming (strong) references. This is to prevent you from unintentionally breaking something in another document that might rely on the asset existing.

Did you remove the video reference from the `drafts.b32572a0-8c4f-43f5-acc1-edf0f6ac9b64` document?

**Comment by patrickdaley** [comment] 2020-02-24 19:13
Hi @kmelve! That reference is the active draft. Because you need to be in the interface for adding the asset to remove it, it's counted as referenced by the same draft you're trying to use to remove it. Hope that makes sense!

**Comment by israelroldan** [comment] 2020-09-13 12:41
+1 that currently open draft is preventing the item from being removed

**Comment by kfrederix** [comment] 2020-09-24 22:28
I can also confim that this makes it kind of impossible to remove a video from the studio interface.

**Comment by KimPaow** [comment] 2021-01-05 14:24
I would also like to bump this. Is there a timeframe for when we can expect this to be fixed or does anyone have a workaround?

**Comment by KimPaow** [comment] 2021-01-07 01:20
I needed this for a client asap so I published a fork to npm with some updates. Rush-job so not 100% tested yet but seems to work so far. I added the new sanity ui components and fixed some visual bugs too (checkbox labels not visible etc).

If you're reading this and are in the same situation - please feel free to try it out by running `sanity install @kimpaow/sanity-plugin-mux-video-input`. Hopefully the official version gets an update soon though!

**Comment by mornir** [comment] 2021-03-03 16:04
@KimPaow Thanks for the fork! Working great so far! 😃

**Comment by gristleism** [comment] 2021-10-05 14:34
Struggling with this today, client can't remove a video from their page so I had to go into the frontend codebase and disable it manually, very frustrating.

**Comment by dylanjha** [comment] 2021-10-05 14:37
@gristleism what version of the plugin are you on? I believe this was added back since v1.0.0

**Comment by gristleism** [comment] 2021-10-05 15:02
My `package.json` file says it should be loading `^1.0.1`.

**Comment by KimPaow** [comment] 2021-10-05 15:51
Yep, this was added since v1.0.0.

@gristleism could you also share what version of the studio you have?

**Comment by gristleism** [comment] 2021-10-05 15:53
@KimPaow happy to! Would you mind letting me know where I can find which version of the studio I'm using?

**Comment by KimPaow** [comment] 2021-10-05 16:00
@gristleism you can run `sanity versions` in the terminal and share the output or check your `@sanity` deps from package.json

**Comment by gristleism** [comment] 2021-10-05 16:08
Results from initial run:

```
@sanity/cli             2.18.0 (latest: 2.20.0)
@sanity/base            2.18.0 (latest: 2.20.0)
@sanity/cli             2.18.0 (latest: 2.20.0)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.18.0 (latest: 2.20.0)
@sanity/default-layout  2.18.0 (latest: 2.20.0)
@sanity/default-login   2.18.0 (latest: 2.19.0)
@sanity/desk-tool       2.18.0 (latest: 2.20.0)
@sanity/vision          2.17.2 (latest: 2.20.0)
```

I then ran `sanity upgrade` and afterwards here are the versions: 

```
@sanity/cli             2.18.0 (latest: 2.20.0)
@sanity/base            2.20.0 (up to date)
@sanity/cli             2.20.0 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.20.0 (up to date)
@sanity/default-layout  2.20.0 (up to date)
@sanity/default-login   2.19.0 (up to date)
@sanity/desk-tool       2.20.0 (up to date)
@sanity/vision          2.20.0 (up to date)
```

Running again locally, I attempted to delete a video file again and received the following error: 

`the mutation(s) failed: Document "d1a72d5b-e897-4ad9-9cb3-7df4c8709afc" cannot be deleted as there are references to it from "frequentlyAskedQuestions"`

**Comment by KimPaow** [comment] 2021-10-05 16:54
@gristleism I just tried running this with the same dependencies you listed here and am unable to reproduce it. Maybe try deleting node-modules and lock files and then reinstall all packages.

If the asset was created using an older version of the plugin (pre v1) this could also be causing problems. To fix that you could delete the old documents and recreate it using v1+ of the plugin. Or you could write a patch to update the asset field on the `mux.video` doc to have the key `weak: true`.

**Comment by JulienDesmettre** [comment] 2022-04-08 16:02
> 
Same "not a bug" issue, but the problem is that i don't anymore have access to the drafts.xxxxxxxxxx, as i made mutations that deleted the schema of  this object/document that refers to the other document i want to delete. So it doesn't exist anymore in my Sanity Studio.  Is there anyway to access it via url and its id drafts.xxxxx ?

**Comment by geball** [comment] 2022-04-09 02:59
@JulienDesmettre You can access the document directly by running `sanity documents create --watch --replace --id 'drafts.xxxxx'` from the terminal.

**Comment by JulienDesmettre** [comment] 2022-04-10 09:00
> @JulienDesmettre You can access the document directly by running `sanity documents create --watch --replace --id 'drafts.xxxxx'` from the terminal.

Thanks for your answer geball. Yes i found it on Sanity CLI doc just few minutes after my question here.

**Comment by jimmi-joensson** [comment] 2022-06-19 08:00
Ran into this issue as well. The issue happens when the `mux.video` is used inside of a schema with the type `array` which includes Portable Text for site building which does not seem optimal.

I made a quick hacked solution by adding `mux.video` to a document solely to delete my videos.

Here is a small screen recording for reference:
https://user-images.githubusercontent.com/15996198/174471561-bdd56ce4-755c-4795-ba74-e4be88d1dc99.mp4

**Comment by jjjuulliiaann** [comment] 2022-07-13 07:41
I have the same issue. As described by @jimmi-joensson it is impossible to delete videos inside the studio, because they have to be added to a document to access the delete button (and therefore can't be deleted as there are references to it).

Maybe it would be a good idea to have a delete button inside the browse/select grid (just like we have inside the image select grid)

<img width="207" alt="Bildschirmfoto 2022-07-13 um 09 40 26" src="https://user-images.githubusercontent.com/47448406/178678431-9573e715-4137-4a91-a80f-ab4a22e6cbf6.png">

**Comment by MichaelPrecel** [comment] 2022-11-07 01:48
Did anyone manage to find a way through this? Multiple versions later and this is still a problem, totally unable to remove a video from a field. Seems to be a very core functionality that bugs out and certainly getting in the way of using Mux in this project.

**Comment by rylanharper** [comment] 2022-11-10 01:04
Has anyone figured out a solution to this? 

I am in the same boat as others above... The plugin still does not allow a video to be removed and when I create a separate module/page section containing a mux component, the plugin breaks with a `Mutation(s) failed with 1 error(s)` Client Error: 
```
POST https://*studio-code*.api.sanity.io/v2021-05-17/data/mutate/production?tag=sanity.studio&returnIds=true&returnDocuments=true&visibility=sync 409
```
On top of this, if I delete a video within the Mux dashboard the videos are not updated within the `Select Videos` tab. Unfortunately this means that instead of using Mux for a client, I am going with Vimeo most likely (which isn't bad, but not ideal).

@kmelve is there any timeframe on this fix? This is the only breaking change that is really holding many developers back from using this plugin/going with Mux over another video service.

**Comment by kwanso-nadeem** [comment] 2022-12-13 07:23
Facing the exact same issue on my end as well. Unable to remove a video. Looking for a fix.

**Comment by jjjuulliiaann** [comment] 2022-12-13 13:28
It does seem to work in the new Sanity Studio v3 using version 2.0.2 of the plugin. The videos in the select grid have a delete option where you can delete the video from the dataset and also from Mux.

**Comment by hdoro** [comment] 2024-02-20 18:07
Closing this issue as deleting assets is now fully supported and respects strong references being used.

Thank you all for showing up, keeping track of updates and helping debug 🙏

**Closed by hdoro** 2024-02-20 18:07 UTC
Labels: triaged
