### ISSUE TITLE
Input field logs error to console on each render

### ISSUE THREAD

**Issue by eriklindebratt** [sanity-io/sanity-plugin-mux-input#30] opened 2021-05-06 09:02 UTC
Each time the video input field is rendered (e.g. when editing a document containing a field of type `mux.video`, an error is logged to the console

> Error: Invalid call to useReporter(field-video): A component reporting on "field-video" is already mounted in the subtree. Make sure that all reporters within the same <Tracker> subtree have unique ids.

…where `field-video` will be called something else depending on what you've named your `mux.video` field in your document schema (mine is called `video` – renaming that field will just log a similar message but e.g. `useReporter(field-someOtherFieldName)`.

**Comment by rafaelmonroy** [comment] 2021-06-23 02:59
@eriklindebratt did you figure out what was causing the issue? Currently experiencing the same bug, I can upload videos to Mux through sanity but can't select them from the library once uploaded. Getting this error message when I try selecting 

`Uncaught TypeError: Cannot read property 'from' of undefined`

I'm thinking these errors might be related

**Comment by KimPaow** [comment] 2021-06-23 07:57
@rafaelmonroy What version of sanity are you using? v1.0.0 of this plugin has a peerDependency of "@sanity/base": "^2.11.0".

The issue you are experiencing is most likely because you're using an older version which doesn't include all the features from sanity/ui this plugin is using.

**Comment by rafaelmonroy** [comment] 2021-06-23 17:08
@KimPaow I'm using `"@sanity/base": "^2.12.2"`

I noticed, the error 

`Invalid call to useReporter(field-video): A component reporting on "field-video" is already mounted in the subtree. Make sure that all reporters within the same <Tracker> subtree have unique ids.`

only gets logged after I enter the token and secret. 

I can upload videos fine, but running into issues using the browse feature, before I couldn't select them, now they don't show up at all.

**Comment by eriklindebratt** [comment] 2021-07-01 08:33
> @eriklindebratt did you figure out what was causing the issue? Currently experiencing the same bug, I can upload videos to Mux through sanity but can't select them from the library once uploaded. Getting this error message when I try selecting
> 
> `Uncaught TypeError: Cannot read property 'from' of undefined`
> 
> I'm thinking these errors might be related

@rafaelmonroy No, I did not unfortunately.

**Comment by ringods** [comment] 2022-01-28 10:41
Error still occurs. Today, I used the FormBuilder API, according [this section in the docs](https://www.sanity.io/docs/custom-input-widgets#40b31a232a03), to display my custom type in my plugin:

https://github.com/ringods/sanity-plugin-github/commit/ef38cb5c91ef55578fe9abf5eeddb59a7ed8fdc7

When I edit an instance of my type, once the input component renders, I get this error a number of times in the web console:

```
Error: Invalid call to useReporter(field-body[_key=="c330b9a07ae5"]): A component reporting on "field-body[_key=="c330b9a07ae5"]" is already mounted in the subtree. Make sure that all reporters within the same <Tracker> subtree have unique ids.
    add createStore.js:30
    useReporter createUseReporter.js:42
    React 7
    unstable_runWithPriority scheduler.development.js:653
    React 5
    unstable_runWithPriority scheduler.development.js:653
    React 6
createStore.js:30
    add createStore.js:30
    useReporter createUseReporter.js:42
    React 7
    unstable_runWithPriority scheduler.development.js:653
    React 5
    unstable_runWithPriority scheduler.development.js:653
    React 6
```

The error and the values shown are always the same.

My input component works correctly though.

Context:

* "@sanity/base": "^2.23.3"
* "@sanity/cli": "^2.23.3"
* "@sanity/components": "^2.14.0"
* "@sanity/core": "^2.23.2"
* "@sanity/dashboard": "^2.23.3"
* "@sanity/default-layout": "^2.23.3"
* "@sanity/default-login": "^2.23.2"
* "@sanity/desk-tool": "^2.23.4"
* "@sanity/form-builder": "^2.24.0"
* "@sanity/studio-hints": "^2.23.0"

Versions in the lock file exactly the same as from `package.json`

**Comment by jfulse** [comment] 2022-08-24 11:29
Not sure if related but I got rid of this error by setting `__unstable_changeIndicator={false}` on a `<FormField>` (imported as import { FormField } from "@sanity/base/components";)

**Comment by hdoro** [comment] 2024-05-20 19:59
Closing as I couldn't reproduce this as of version `2.4.0` and Sanity `3.42.0`.

Reply in this issue and tag me if you have a reproduction and I should re-open and investigate it 🙏

**Closed by hdoro** 2024-05-20 19:59 UTC
Labels: triaged
