### ISSUE TITLE
Audio-only files now producing error: right-hand side of 'instanceof' is not an object 

### ISSUE THREAD

**Issue by sharpsteelsoftware1** [sanity-io/sanity-plugin-mux-input#224] opened 2023-03-01 01:36 UTC
Dragging a WAV onto the video player used to work throughout the entire chain of events. I am not sure changed, but just recently now I am getting "right-hand side of 'instanceof' is not an object " when dropping a WAV onto the file upload just after it completes uploading.

**Comment by israelroldan** [comment] 2023-03-09 19:02
This is a regression from v2.0.10 onwards. Introduced by the upgrade of jsonwebtoken-esm to 2.x which contains a breaking change: https://github.com/auth0/node-jsonwebtoken/pull/852

**Comment by israelroldan** [comment] 2023-03-09 19:08
@stipsan To elaborate on my comment above:

This regression was introduced by this commit from renovate: https://github.com/sanity-io/sanity-plugin-mux-input/commit/d13760fa540bb3c5e9a68283f7b5f00e9e40f4fb

A temporary fix is to downgrade to 2.0.9, but a structural fix is to ensure the key passed to sign the JWT is an isntance of crypto's KeyObject and not a string as currently ([here](https://github.com/sanity-io/sanity-plugin-mux-input/blob/8ff31afa8ec564040ddbed454ac59e8feaa195a3/src/util/generateJwt.ts#L37)) that like should most likely be: `KeyObject.from(atob(signingKeyPrivate))` instead of just `atob(signingKeyPrivate)`

**Comment by israelroldan** [comment] 2023-03-13 19:51
In case anyone sees that, there's another bug in version 2.0.9. So I took a look and version 2.0.12 seems to be the last one without this problem. at least it is working for our setup. It may be of help for you @sharpsteelsoftware1

**Comment by jonabc** [comment] 2023-06-19 21:42
I believe this was fixed in https://github.com/sanity-io/sanity-plugin-mux-input/pull/253.  If you're still seeing this issue in recent versions please reopen 🙏

**Closed by jonabc** 2023-06-19 21:42 UTC
