### ISSUE TITLE
Cannot read properties of undefined (reading 'dataset')

### ISSUE THREAD

**Issue by Olalexy1** [sanity-io/sanity-plugin-mux-input#328] opened 2023-10-23 02:14 UTC
Good day Admin, 

I have been having this issue trying to use the sanity-plugin-mux-input for a while now. Pls how can I fix this issue

![Screenshot 2023-10-23 022812](https://github.com/sanity-io/sanity-plugin-mux-input/assets/91855086/a6732330-510a-44d5-b66d-903501b70400)

**Comment by JamesGriz** [comment] 2023-10-30 06:57
Was having the same issue last week but tested again and seems to now be working fine, not sure what changed

**Comment by kennynumbertwo** [comment] 2023-11-14 04:57
I have been running into this same problem. Any luck on a solution?

**Comment by Olalexy1** [comment] 2023-11-15 15:18
Honestly, I am unsure what I did to get it to work, but could you make sure the dataset in your sanity config file is the same as the dataset on Mux. For example if 'production' or 'development' on sanity do the same dataset on Mux. Hope that helps, you can probably let me know if it works and maybe we can check through. Goodluck

**Comment by JVPortage** [comment] 2024-01-12 14:19
I was having this problem too.  I re-ran `yarn install` on my local studio and deployed.  This seemed to fix the problem.

**Comment by hdoro** [comment] 2024-02-20 18:28
Duplicate of #277

**Closed by hdoro** 2024-02-20 18:28 UTC
