### ISSUE TITLE
Embedding Sanity does not work with Mux Input v2.0.15

### ISSUE THREAD

**Issue by dictions** [sanity-io/sanity-plugin-mux-input#252] opened 2023-04-03 18:27 UTC
```
./node_modules/sanity-plugin-mux-input/lib/_chunks/Input-509c8fa5.cjs:1:1110
Module not found: ESM packages (media-chrome/dist/react) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/sanity-plugin-mux-input/lib/_chunks/index-d360f7ae.cjs
./node_modules/sanity-plugin-mux-input/lib/index.cjs
./node_modules/sanity-plugin-mux-input/lib/index.cjs.js
./sanity.config.js
./src/app/admin/[[...index]]/page.jsx
```
<img width="984" alt="CleanShot 2023-04-03 at 14 27 00@2x" src="https://user-images.githubusercontent.com/4307278/229595403-126c03f0-14fa-4595-8566-2182459ec41e.png">

**Comment by danteissaias** [comment] 2023-04-24 15:31
Did you manage to find a solution for this?

**Comment by JoeMatkin** [comment] 2023-05-11 14:27
Also facing this issue

**Comment by mshnp** [comment] 2023-05-19 19:00
also facing this issue

**Comment by davekiss** [comment] 2023-05-22 13:54
Hey all, does anyone have a repo they can share to reproduce the issue? My guess is this is being embedded in a Next.js environment and the media-chrome exports aren't resolving the same way.

As per a suggestion from @cjpilsbury you can also try adding this to your `next.config.js`

```json
...,
experimental: {
  esmExternals: 'loose'
}
```

**Comment by danteissaias** [comment] 2023-05-22 13:58
@davekiss `media-chrome` does not define the `exports` field in it's `package.json`. It's `main` field points to an ESM module therefore it will not resolve correctly in a CJS environment. See https://github.com/sanity-io/sanity-plugin-mux-input/issues/252#issuecomment-1557264695

**Comment by cjpillsbury** [comment] 2023-05-22 14:27
@danteissaias unfortunately it's a bit more complex for this case, which uses the react wrapper that does not currently have a CJS equivalent. See: https://github.com/sanity-io/sanity-plugin-mux-input/blob/c5582c54a1c985c4e7c5d62e31b7b4f8cad1ac1d/src/components/Player.tsx#L13

**Comment by marnauortega** [comment] 2023-05-23 14:40
@davekiss and @cjpillsbury thanks a lot for your suggestions. I tried adding `esmExternals: 'loose'` and it solved the problem!

Still, I made a simple repo with next and sanity embedded studio, so that if you need to reproduce the error you can easily do it. (If you add the `esmExternals: 'loose'` you'll see it's fixed.) Here it is: https://github.com/marnauortega/next-sanity-mux-test

**Comment by Rasheed124** [comment] 2023-06-18 21:31
Thanks very much @davekiss. This worked for me

**Comment by hdoro** [comment] 2024-05-03 11:47
Duplicate of #274

**Closed by hdoro** 2024-05-03 11:47 UTC
Labels: triaged
