### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'dataset')

### ISSUE THREAD

**Issue by Vintotan** [sanity-io/sanity-plugin-mux-input#277] opened 2023-05-23 12:45 UTC
Seems like the problem is not solved ...
<img width="1920" alt="Screenshot 2023-05-23 at 10 23 57" src="https://github.com/sanity-io/sanity-plugin-mux-input/assets/39995527/7bc388ad-912a-4cdb-88a8-1689040453a4">
<img width="1440" alt="Screenshot 2023-05-23 at 10 55 08" src="https://github.com/sanity-io/sanity-plugin-mux-input/assets/39995527/82e7876f-2c2b-4a25-9735-4e812774fa97">

For reproducing the issue you can find my project here:
https://github.com/streamify-com/sanity-next-mux

_Originally posted by @Vintotan in https://github.com/sanity-io/sanity-plugin-mux-input/issues/215#issuecomment-1559227574_

**Comment by vedantkarle** [comment] 2023-05-28 12:26
Same Problem for me as well
![image](https://github.com/sanity-io/sanity-plugin-mux-input/assets/59387428/9047aca7-8b6a-4b67-bc19-7008da9fd9aa)

**Comment by sebpowell** [comment] 2023-06-15 20:16
Got it working by doing this: https://github.com/sanity-io/sanity-plugin-mux-input/issues/274#issuecomment-1559573137, and installing  `"sanity-plugin-mux-input": "^2.0.17"`,  instead of `"sanity-plugin-mux-input": "2.0.0-v3-studio.22"`.

**Comment by sebpowell** [comment] 2023-06-16 17:19
@Vintotan – thank you! Yep, tried that yesterday and it worked, thanks for your help.

**Comment by dustin100** [comment] 2023-09-05 19:27
Is there a solution to this when using React and vite?

downgrading to v2 worked, but I'd rather not do that.

**Comment by billyberkouwer** [comment] 2023-09-19 11:10
I am having the same issue. I have a Sanity v3/Next.js 13.4.19 site and am getting the following error:

![image](https://github.com/sanity-io/sanity-plugin-mux-input/assets/76756401/cadca699-5157-4a37-9026-8576849023e0)

It isn't possible to upload URLs or videos because the Mux dataset is undefined. I have tried adding   
 
```
experimental: {
        esmExternals: 'loose'
}
```
to my next.config.js but this doesn't solve the problem. As a last resort, I tried using an older version of mux-input with legacy peer dependencies, and although this gets resolves the dataset undefined error, it produces another error due to a `TypeError: styled_components_cjs is not a function` which fails the build in production

**Comment by moreguppy** [comment] 2023-11-08 09:31
Also encountering this issue on `next@^13.5.6` and `sanity-plugin-mux-input@^2.0.0-v3-studio.22`

**Comment by hdoro** [comment] 2024-05-20 20:05
The reproduction is not available anymore and it's been a while since the last time this error was reported.

As of Next `14.2.1`, Sanity `3.42.0` and `sanity-plugin-mux-input@2.4.0` I couldn't reproduce it.

Closing the issue - if the problem persists, please reply with a reproduction tag me to re-open it 🙏

**Closed by hdoro** 2024-05-20 20:05 UTC
Labels: triaged
